# Generated by Claude Code (claude-sonnet-4-5@20250929)
"""
Tests for team role assignment validation that restricts team assignments
to galaxy-only roles.
"""

import pytest

from ansible_base.lib.utils.response import get_relative_url
from ansible_base.rbac.models import DABContentType, DABPermission, RoleDefinition
from test_app.models import Organization


@pytest.fixture
def galaxy_content_type():
    """Create a galaxy content type for testing."""
    org_ct = DABContentType.objects.get_for_model(Organization)
    return DABContentType.objects.create(service='galaxy', model='collectionremote', app_label='galaxy', pk_field_type='uuid', parent_content_type=org_ct)


@pytest.fixture
def galaxy_permissions(galaxy_content_type):
    """Create permissions for the galaxy content type."""
    view_perm = DABPermission.objects.create(codename='view_collectionremote', content_type=galaxy_content_type, name='Can view collection remote')
    change_perm = DABPermission.objects.create(codename='change_collectionremote', content_type=galaxy_content_type, name='Can change collection remote')
    return view_perm, change_perm


@pytest.fixture
def galaxy_role(galaxy_content_type, galaxy_permissions):
    """Create a role definition with only galaxy permissions."""
    view_perm, change_perm = galaxy_permissions
    return RoleDefinition.objects.create_from_permissions(
        name='Galaxy Collection Remote Admin', permissions=[view_perm.api_slug, change_perm.api_slug], content_type=galaxy_content_type
    )


@pytest.fixture
def platform_auditor_role():
    """Get or create the Platform Auditor role which has non-galaxy permissions."""
    try:
        return RoleDefinition.objects.get(name='Platform Auditor')
    except RoleDefinition.DoesNotExist:
        # Create a simplified version for testing if it doesn't exist
        # This role should have permissions from the local service, not galaxy
        return RoleDefinition.objects.create_from_permissions(
            name='Platform Auditor', permissions=['view_inventory', 'view_organization'], content_type=None  # Global role
        )


@pytest.mark.django_db
def test_team_cannot_receive_platform_auditor_role(admin_api_client, team, platform_auditor_role):
    """
    Test that the Platform Auditor role cannot be assigned to a team
    because it contains non-galaxy permissions.
    """
    url = get_relative_url('roleteamassignment-list')
    response = admin_api_client.post(url, data={'role_definition': platform_auditor_role.id, 'team': team.id}, format='json')

    assert response.status_code == 400, response.data
    assert 'role_definition' in response.data
    assert 'galaxy service' in str(response.data['role_definition']).lower()


@pytest.mark.django_db
def test_team_can_receive_galaxy_role(admin_api_client, team, galaxy_role, galaxy_content_type):
    """
    Test that a galaxy-only role can be assigned to a team through
    the team-role-assignments endpoint.
    """
    # Create a test object ID for the galaxy content type
    import uuid

    collection_uuid = uuid.uuid4()

    url = get_relative_url('roleteamassignment-list')
    response = admin_api_client.post(url, data={'role_definition': galaxy_role.id, 'team': team.id, 'object_id': str(collection_uuid)}, format='json')

    assert response.status_code == 201, response.data
    assert response.data['role_definition'] == galaxy_role.id
    assert response.data['team'] == team.id


@pytest.mark.django_db
def test_team_cannot_receive_mixed_service_role(admin_api_client, team, galaxy_permissions):
    """
    Test that a role with mixed galaxy and non-galaxy permissions
    cannot be assigned to a team.
    """
    # Create a role with both galaxy and non-galaxy permissions
    view_perm, change_perm = galaxy_permissions
    mixed_role = RoleDefinition.objects.create_from_permissions(
        name='Mixed Service Role',
        permissions=[view_perm.api_slug, 'view_inventory'],  # galaxy permission  # non-galaxy permission
        content_type=None,  # Global role
    )

    url = get_relative_url('roleteamassignment-list')
    response = admin_api_client.post(url, data={'role_definition': mixed_role.id, 'team': team.id}, format='json')

    assert response.status_code == 400, response.data
    assert 'role_definition' in response.data
    assert 'galaxy service' in str(response.data['role_definition']).lower()
    # Should mention the non-galaxy permissions
    assert 'view_inventory' in str(response.data['role_definition'])
