# Generated by Claude Sonnet 4
import logging
import time
from unittest.mock import patch

import pytest
from django.test import TestCase, override_settings

from ansible_base.lib.utils.performance import (
    enable_performance_logging,
    measure_post_migrate_signal,
    measure_time,
    patch_post_migrate_handlers,
)


class TestPerformanceMeasurement(TestCase):
    """Test the performance measurement utilities."""

    def test_measure_time_context_manager(self):
        """Test that measure_time context manager logs execution time."""
        with self.assertLogs('ansible_base.performance', level='INFO') as cm:
            with measure_time("test_operation"):
                time.sleep(0.01)  # Small delay to ensure measurable time
        
        self.assertEqual(len(cm.output), 1)
        self.assertIn("[PERFORMANCE] test_operation:", cm.output[0])
        # Should show some positive time duration
        self.assertRegex(cm.output[0], r'\d+\.\d{4}s')

    def test_measure_post_migrate_signal_decorator(self):
        """Test that the post_migrate signal decorator works correctly."""
        
        @measure_post_migrate_signal
        def dummy_post_migrate_handler(sender, **kwargs):
            time.sleep(0.01)  # Small delay
            return "test_result"
        
        with self.assertLogs('ansible_base.performance', level='INFO') as cm:
            result = dummy_post_migrate_handler(sender=None)
        
        self.assertEqual(result, "test_result")
        self.assertEqual(len(cm.output), 1)
        self.assertIn("post_migrate: test_app.tests.lib.utils.test_performance.dummy_post_migrate_handler", cm.output[0])

    def test_enable_performance_logging(self):
        """Test that enable_performance_logging sets up the logger correctly."""
        # Get the logger before enabling
        logger = logging.getLogger('ansible_base.performance')
        original_level = logger.level
        original_handlers = list(logger.handlers)
        
        try:
            enable_performance_logging()
            
            # Check that the logger is set to INFO level
            self.assertEqual(logger.level, logging.INFO)
            
            # Check that a handler was added if none existed
            if not original_handlers:
                self.assertTrue(len(logger.handlers) > 0)
        
        finally:
            # Restore original state
            logger.setLevel(original_level)
            logger.handlers = original_handlers

    @patch('ansible_base.rbac.management.create_dab_permissions')
    @patch('ansible_base.rbac.triggers.post_migration_rbac_setup')
    @patch('ansible_base.resource_registry.apps.initialize_resources')
    @patch('ansible_base.resource_registry.apps.connect_resource_signals')
    def test_patch_post_migrate_handlers(self, mock_connect, mock_init, mock_rbac, mock_perms):
        """Test that patch_post_migrate_handlers patches the handlers."""
        # Mock the original functions
        def original_func():
            return "original"
        
        mock_connect.return_value = original_func
        mock_init.return_value = original_func
        mock_rbac.return_value = original_func
        mock_perms.return_value = original_func
        
        with self.assertLogs('ansible_base.performance', level='INFO') as cm:
            patch_post_migrate_handlers()
        
        # Check that the patching was logged
        patch_logged = any("Post-migrate signal handlers patched" in output for output in cm.output)
        self.assertTrue(patch_logged, "Patching should have been logged")

    @override_settings(ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE=True)
    def test_performance_measurement_setting(self):
        """Test that the setting enables performance measurement."""
        from django.conf import settings
        self.assertTrue(getattr(settings, 'ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE', False))


class TestPerformanceMeasurementIntegration(TestCase):
    """Integration tests for performance measurement with Django signals."""
    
    @override_settings(ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE=True)
    def test_performance_measurement_with_setting_enabled(self):
        """Test that performance measurement works when the setting is enabled."""
        # This test verifies the integration works, but doesn't run actual migrations
        # as that would be too complex for a unit test
        from django.conf import settings
        self.assertTrue(getattr(settings, 'ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE', False))