# Generated by Claude Sonnet 4
"""
Test configuration to enable post_migrate performance measurement.

To use this in your tests or CI, add to your Django settings:

    # Enable post_migrate performance measurement
    ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE = True
    
    # Optional: Configure logging level for performance measurements
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'performance': {
                'format': '[{asctime}] {levelname} {name}: {message}',
                'style': '{',
            },
        },
        'handlers': {
            'performance_console': {
                'class': 'logging.StreamHandler',
                'formatter': 'performance',
            },
        },
        'loggers': {
            'ansible_base.performance': {
                'handlers': ['performance_console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }

Example output when enabled:
    [2025-08-21 10:30:15,123] INFO ansible_base.performance: [PERFORMANCE] post_migrate: ansible_base.rbac.management.create_dab_permissions: 0.0234s
    [2025-08-21 10:30:15,456] INFO ansible_base.performance: [PERFORMANCE] post_migrate: ansible_base.rbac.triggers.post_migration_rbac_setup: 0.1234s
    [2025-08-21 10:30:15,678] INFO ansible_base.performance: [PERFORMANCE] post_migrate: ansible_base.resource_registry.apps.initialize_resources: 0.0456s
    [2025-08-21 10:30:15,789] INFO ansible_base.performance: [PERFORMANCE] post_migrate: ansible_base.resource_registry.apps.connect_resource_signals: 0.0123s
"""

# Example settings that can be imported in test configurations
PERFORMANCE_MEASUREMENT_SETTINGS = {
    'ANSIBLE_BASE_MEASURE_POST_MIGRATE_PERFORMANCE': True,
    'LOGGING': {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'performance': {
                'format': '[{asctime}] {levelname} {name}: {message}',
                'style': '{',
            },
        },
        'handlers': {
            'performance_console': {
                'class': 'logging.StreamHandler',
                'formatter': 'performance',
            },
        },
        'loggers': {
            'ansible_base.performance': {
                'handlers': ['performance_console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
}