# Generated by Claude Sonnet 4
import logging
import time
from contextlib import contextmanager
from functools import wraps

logger = logging.getLogger('ansible_base.performance')


@contextmanager
def measure_time(operation_name):
    """Context manager to measure and log execution time of operations."""
    start_time = time.perf_counter()
    try:
        yield
    finally:
        end_time = time.perf_counter()
        duration = end_time - start_time
        logger.info(f"[PERFORMANCE] {operation_name}: {duration:.4f}s")


def measure_post_migrate_signal(func):
    """Decorator to measure post_migrate signal handler execution time."""
    @wraps(func)
    def wrapper(*args, **kwargs):
        func_name = f"{func.__module__}.{func.__name__}"
        with measure_time(f"post_migrate: {func_name}"):
            return func(*args, **kwargs)
    return wrapper


def patch_post_migrate_handlers():
    """
    Monkey patch existing post_migrate signal handlers to add performance measurement.
    This should be called early in Django startup to capture all handlers.
    """
    # Import the handlers we want to measure
    try:
        from ansible_base.rbac.management import create_dab_permissions
        from ansible_base.rbac.triggers import post_migration_rbac_setup
        from ansible_base.resource_registry.apps import initialize_resources, connect_resource_signals
        
        # Patch the handlers
        import ansible_base.rbac.management
        import ansible_base.rbac.triggers
        import ansible_base.resource_registry.apps
        
        ansible_base.rbac.management.create_dab_permissions = measure_post_migrate_signal(create_dab_permissions)
        ansible_base.rbac.triggers.post_migration_rbac_setup = measure_post_migrate_signal(post_migration_rbac_setup)
        ansible_base.resource_registry.apps.initialize_resources = measure_post_migrate_signal(initialize_resources)
        ansible_base.resource_registry.apps.connect_resource_signals = measure_post_migrate_signal(connect_resource_signals)
        
        logger.info("[PERFORMANCE] Post-migrate signal handlers patched for performance measurement")
        
    except ImportError as e:
        logger.warning(f"[PERFORMANCE] Could not patch post_migrate handlers: {e}")


def enable_performance_logging():
    """Enable performance logging by setting appropriate log levels."""
    perf_logger = logging.getLogger('ansible_base.performance')
    perf_logger.setLevel(logging.INFO)
    
    # Add a handler if none exists and prevent propagation to avoid duplicates
    if not perf_logger.handlers:
        handler = logging.StreamHandler()
        formatter = logging.Formatter('[%(asctime)s] %(levelname)s %(name)s: %(message)s')
        handler.setFormatter(formatter)
        perf_logger.addHandler(handler)
        perf_logger.propagate = False