# Generated by Claude Sonnet 4
"""
Test to verify that RBAC does not allow permission assignment to users that
the requesting user cannot view through the visible_users policy.
"""
import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient

from ansible_base.rbac.models import RoleUserAssignment
from ansible_base.rbac.policies import visible_users

User = get_user_model()


@pytest.mark.django_db
class TestAssignmentVisibilitySecurity:
    """Test that users cannot assign permissions to users they cannot see"""

    def test_cannot_assign_permission_to_invisible_user(self, inventory, inv_rd, user, organization):  # This is the authenticated user from the fixture
        """
        Test that a user with admin permission to an inventory cannot assign
        permissions to a user they cannot see via the visible_users method.

        This is a security test to ensure RBAC doesn't allow privilege escalation
        by granting permissions to users the requester shouldn't be able to see.
        """
        # Create a second user that the authenticated user should NOT be able to see
        invisible_user = User.objects.create(username='invisible_user', email='invisible@example.com')

        # Verify that the invisible user is not in the visible users for the authenticated user
        visible_qs = visible_users(user)
        assert invisible_user not in visible_qs, "Test setup failed: invisible_user should not be visible to authenticated user"

        # Give the authenticated user admin permission to the inventory
        RoleUserAssignment.objects.create(user=user, role_definition=inv_rd, content_object=inventory)

        # Create authenticated API client for the user
        client = APIClient()
        client.force_authenticate(user=user)

        # Attempt to assign the inventory role to the invisible user
        assignment_data = {'user': invisible_user.pk, 'role_definition': inv_rd.pk, 'object_id': inventory.pk}

        response = client.post('/api/v1/role_user_assignments/', assignment_data, format='json')

        # The assignment should be rejected due to security policy
        # Either with 400 (validation error) or 404 (user not found/accessible)
        assert response.status_code in [400, 404], (
            f"Expected 400 or 404 when trying to assign permission to invisible user, " f"got {response.status_code}: {response.data}"
        )

        # Verify no assignment was actually created
        from ansible_base.rbac.models import DABContentType

        assignment_exists = RoleUserAssignment.objects.filter(
            user=invisible_user, role_definition=inv_rd, content_type=DABContentType.objects.get_for_model(inventory.__class__), object_id=inventory.pk
        ).exists()

        assert not assignment_exists, "Assignment should not have been created for invisible user"

    def test_both_users_can_see_each_other_when_superuser(self, inventory, inv_rd, user, organization):  # authenticated user
        """
        Simplified control test: verify that a superuser can assign to any user.
        """
        # Make the authenticated user a superuser
        user.is_superuser = True
        user.save()

        # Create a second user (superuser should be able to see and assign to any user)
        visible_user = User.objects.create(username='visible_user', email='visible@example.com')

        # Give the authenticated user admin permission to the inventory
        RoleUserAssignment.objects.create(user=user, role_definition=inv_rd, content_object=inventory)

        # Create authenticated API client for the user
        client = APIClient()
        client.force_authenticate(user=user)

        # Attempt to assign the inventory role to the visible user
        assignment_data = {'user': visible_user.pk, 'role_definition': inv_rd.pk, 'object_id': inventory.pk}

        response = client.post('/api/v1/role_user_assignments/', assignment_data, format='json')

        # This should succeed for superuser
        assert response.status_code == 201, f"Expected 201 when superuser assigns permission to user, " f"got {response.status_code}: {response.data}"

        # Verify the assignment was created
        from ansible_base.rbac.models import DABContentType

        assignment_exists = RoleUserAssignment.objects.filter(
            user=visible_user, role_definition=inv_rd, content_type=DABContentType.objects.get_for_model(inventory.__class__), object_id=inventory.pk
        ).exists()

        assert assignment_exists, "Assignment should have been created for visible user"


@pytest.mark.django_db
def test_org_admin_access_to_role_user_access_endpoint(user_api_client, user, org_admin_rd):
    """
    Test that an organization admin can access the role_user_access endpoint for their organization.

    This tests for a bug where org admins get a 403 error when accessing:
    GET /api/gateway/v1/role_user_access/shared.organization/2/
    """
    from ansible_base.lib.utils.response import get_relative_url
    from test_app.models import Organization

    # Create an organization
    organization = Organization.objects.create(name='test-org')

    # Give the user org admin permissions for this organization
    org_admin_rd.give_permission(user, organization)

    # Construct the URL for the role_user_access endpoint
    url = get_relative_url('role-user-access', kwargs={'pk': organization.pk, 'model_name': 'shared.organization'})

    # Make the request as the org admin user
    response = user_api_client.get(url)

    # This should NOT return 403 - org admins should be able to access this endpoint
    assert response.status_code != 403, f"Organization admin got 403 error accessing role_user_access endpoint: {response.data}"

    # It should return 200 OK
    assert response.status_code == 200, f"Expected 200 but got {response.status_code}: {response.data}"
