# Generated by Django 4.2.8 on 2024-01-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '__first__'),  # needs to be a separate migration because of this dependency
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='singleton_roles',
            field=models.ManyToManyField(blank=True, to='dab_rbac.roledefinition'),
        ),
        migrations.AddField(
            model_name='user',
            name='singleton_roles',
            field=models.ManyToManyField(blank=True, related_name='singleton_users', to='dab_rbac.roledefinition'),
        ),
    ]
