# Generated by Django 4.2.8 on 2024-01-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0001_initial'),
        ('test_app', '0002_main_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='singleton_roles',
            field=models.ManyToManyField(blank=True, to='dab_rbac.roledefinition'),
        ),
        migrations.AlterField(
            model_name='user',
            name='singleton_roles',
            field=models.ManyToManyField(blank=True, related_name='singleton_users', to='dab_rbac.roledefinition'),
        ),
    ]
