# Generated by Django 4.2.8 on 2024-01-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_singleton_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
    ]
