# Generated by Django 4.2.8 on 2024-01-23 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_alter_team_singleton_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_parents',
            field=models.ManyToManyField(blank=True, related_name='team_children', to='test_app.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tracked_users',
            field=models.ManyToManyField(blank=True, related_name='tracked_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
