# Generated by Django 4.2.8 on 2024-03-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_create_system_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='encryptioner',
        ),
    ]
