# Generated by Django 5.2.8 on 2026-03-20 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_app', '0018_alter_animal_created_alter_animal_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this role.', max_length=512, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='A description of what this role grants.')),
                ('managed', models.BooleanField(default=False, help_text='Whether this role is system-managed.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OPAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of this OPA group.', max_length=512)),
                ('managed', models.BooleanField(default=False, help_text='Whether this group is system-managed (e.g. per-user groups).')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization this group belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opa_groups', to='test_app.organization')),
                ('users', models.ManyToManyField(blank=True, help_text='Users in this OPA group.', related_name='dab_opa_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OPA Group',
                'verbose_name_plural': 'OPA Groups',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(help_text='The resource type this policy applies to.', max_length=255)),
                ('action', models.CharField(help_text='The action this policy applies to.', max_length=255)),
                ('field_name', models.CharField(help_text='The field to filter on.', max_length=255)),
                ('operator', models.CharField(choices=[('eq', 'Equals')], default='eq', help_text='The comparison operator.', max_length=20)),
                ('value_type', models.CharField(choices=[('constant', 'Constant value'), ('principal_user_id', "Current user's ID")], help_text='How the comparison value is determined.', max_length=30)),
                ('constant_value', models.TextField(blank=True, help_text="The constant value to compare against (when value_type is 'constant').", null=True)),
                ('position', models.IntegerField(default=0, help_text='Optional ordering position.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='The role this policy belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='dab_opa.role')),
            ],
            options={
                'ordering': ['role', 'resource', 'action', 'position'],
            },
        ),
        migrations.CreateModel(
            name='GroupRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='The group receiving this role.', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='dab_opa.opagroup')),
                ('role', models.ForeignKey(help_text='The role being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='dab_opa.role')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('group', 'role')},
            },
        ),
    ]
