# Generated by Django 4.2.16 on 2025-02-04 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID that corresponds to the dispatcher task uuid', primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('running', 'Running'), ('waiting', 'Waiting')], default='waiting', help_text='Choices of this field track with acknowledgement and completion of a task', max_length=15)),
                ('name', models.TextField(help_text='Importable path for class or method')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time the publisher (submitter) of this task call created it, approximately the time of submission as well')),
                ('started_at', models.DateTimeField(help_text='Time of acknowledgement, also approximately the time the task starts', null=True)),
                ('finished_at', models.DateTimeField(help_text='Time task is cleared (whether failed or succeeded), may be unused if set to auto-delete', null=True)),
            ],
        ),
    ]
