# Generated by Django 4.2.16 on 2025-02-18 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dab_tas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wrapper_uuid',
            field=models.UUIDField(default=None, editable=False, help_text='Adopted UUID of DAB task app wrapper, attached when background service starts task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Original dispatcher UUID generated at time of task publishing', primary_key=True, serialize=False),
        ),
    ]
