# Generated by Django 4.2.16 on 2025-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_tas', '0002_task_wrapper_uuid_alter_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='args',
            field=models.JSONField(blank=True, default=dict, help_text='The arguments for the task run.'),
        ),
        migrations.AddField(
            model_name='task',
            name='kwargs',
            field=models.JSONField(blank=True, default=dict, help_text='The keyword arguments for the task run.'),
        ),
    ]
