# Generated by Django 4.2.16 on 2025-02-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_tas', '0003_task_args_task_kwargs'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue',
            field=models.TextField(default='', help_text='The work queue this task is submitted to, only nodes listening to this queue may process the task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='wrapper_uuid',
            field=models.CharField(blank=True, default='', editable=False, help_text='Adopted UUID of DAB task app wrapper, attached when background service starts task', max_length=40),
        ),
    ]
