from unittest.mock import patch

import pytest
from django.db import IntegrityError

from ansible_base.resource_registry.models.service_identifier import ServiceID, service_id


@pytest.mark.django_db
def test_service_id_already_exists():
    "The resource registry already creates this, so we expect an error here"
    # Ensure one exists first
    if not ServiceID.objects.exists():
        ServiceID.objects.create()
    with pytest.raises(RuntimeError) as exc:
        ServiceID.objects.create()
    assert 'This service already has a ServiceID' in str(exc)


@pytest.mark.django_db
def test_service_id_does_not_yet_exist():
    ServiceID.objects.all().delete()  # clear out any existing
    ServiceID.objects.create()  # expect no error


@pytest.mark.django_db
def test_service_id_function_auto_creates_in_debug():
    """
    Generated by Claude Sonnet 4.5
    Test that service_id() auto-creates ServiceID when none exists in DEBUG/pytest mode.
    """
    # Clear the global cache and delete existing ServiceID
    import sys

    import ansible_base.resource_registry.models.service_identifier as sid_module

    sid_module._service_id = None
    ServiceID.objects.all().delete()

    # Ensure pytest is in sys.argv to trigger auto-creation
    with patch.object(sys, 'argv', ['pytest']):
        result = service_id()

    assert result is not None
    assert ServiceID.objects.count() == 1
    # The service was created successfully


@pytest.mark.django_db
def test_service_id_function_handles_integrity_error():
    """
    Generated by Claude Sonnet 4.5
    Test that service_id() handles IntegrityError when another thread/process creates ServiceID first.
    """
    # Clear the global cache and delete existing ServiceID
    import sys

    import ansible_base.resource_registry.models.service_identifier as sid_module

    sid_module._service_id = None
    ServiceID.objects.all().delete()

    # Pre-create an object to simulate another process winning the race
    # We'll create it before the patched create is called
    ServiceID.objects.create(pk=1)

    # Delete from cache and reset so service_id() will try to create
    sid_module._service_id = None
    # Don't delete from DB - simulate another process created it

    # Mock create to raise IntegrityError
    def mock_create(*args, **kwargs):
        # Raise IntegrityError to simulate race condition
        raise IntegrityError("Duplicate key")

    # Ensure pytest is in sys.argv to trigger auto-creation path
    with patch.object(sys, 'argv', ['pytest']):
        # Mock objects.first() to return None to force the creation path
        with patch.object(ServiceID.objects, 'first', return_value=None):
            with patch.object(ServiceID.objects, 'create', side_effect=mock_create):
                result = service_id()

    assert result is not None
    # The IntegrityError was handled and it fetched the existing record via get(pk=1)
    assert ServiceID.objects.count() == 1
