# Generated by Django 4.2.6 on 2024-06-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dabpermission',
            options={'default_permissions': (), 'ordering': ['content_type__model', 'codename'], 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AlterModelOptions(
            name='roledefinition',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['id'], 'verbose_name_plural': 'role_definition'},
        ),
        migrations.AlterModelOptions(
            name='roleteamassignment',
            options={'default_permissions': ('add', 'delete', 'view'), 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='roleuserassignment',
            options={'default_permissions': ('add', 'delete', 'view'), 'ordering': ['id']},
        ),
    ]
