# Generated by Django 4.2.23 on 2025-06-30 12:48

import ansible_base.rbac.models.content_type
import ansible_base.rbac.remote
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0003_alter_dabpermission_codename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DABContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default=ansible_base.rbac.remote.get_local_resource_prefix, help_text='service namespace to track what service this type is for. Can have a value of shared, which indicates it is synchronized.', max_length=100)),
                ('app_label', models.CharField(help_text='Django app that the model is in. This is an internal technical detail that does not affect API use.', max_length=100)),
                ('model', models.CharField(help_text='Name of the type according to the Django ORM Meta model_name convention. Comes from the python class, but lowercase with no spaces.', max_length=100)),
            ],
            options={
                'unique_together': {('service', 'app_label', 'model')},
            },
            managers=[
                ('objects', ansible_base.rbac.models.content_type.DABContentTypeManager()),
            ],
        ),
    ]
