# Generated by Django 4.2.23 on 2025-06-30 12:48

from django.db import migrations


def create_types_and_permissions(apps, schema_editor):
    """Before we can migrate to the new DABContentType, entries in that table must be created.

    This method runs what is ordinarily the post_migrate logic, but in the migration case here.
    """
    from ansible_base.rbac.management import create_dab_permissions

    create_dab_permissions(apps.get_app_config('dab_rbac'), apps=apps)


def migrate_content_type(apps, schema_editor):
    ct_cls = apps.get_model('dab_rbac', 'DABContentType')
    ct_cls.objects.clear_cache()
    for model_name in ('dabpermission', 'objectrole', 'roledefinition', 'roleuserassignment', 'roleteamassignment'):
        cls = apps.get_model('dab_rbac', model_name)
        for obj in cls.objects.all():
            old_ct = obj.content_type
            if old_ct:
                # NOTE: could give duplicate normally, but that is impossible in migration path
                obj.new_content_type = ct_cls.objects.get_by_natural_key(old_ct.app_label, old_ct.model)
                obj.save()
    for model_name in ('roleevaluation', 'roleevaluationuuid'):
        cls = apps.get_model('dab_rbac', model_name)
        cls.objects.all().delete()

    # DABPermission model had api_slug added in last migration
    # if records existed before this point, it needs to be filled in
    permission_cls = apps.get_model('dab_rbac', 'DABPermission')
    for permission in permission_cls.objects.all():
        permission.api_slug = f'{permission.new_content_type.service}.{permission.codename}'
        permission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0004_remote_permissions_additions'),
    ]

    operations = [
        migrations.RunPython(create_types_and_permissions, migrations.RunPython.noop),
        migrations.RunPython(migrate_content_type, migrations.RunPython.noop),
    ]
