# Generated by Django 4.2.23 on 2025-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0005_remote_permissions_migration'),
    ]

    operations = [
        # After data migration this should be safe to make non-null again
        migrations.AlterField(
            model_name='objectrole',
            name='content_type',
            field=models.ForeignKey(help_text='The content type of the subject of permission assignments. Duplicated from related RoleDefinition.', on_delete=models.deletion.CASCADE, to='dab_rbac.dabcontenttype'),
        ),
        # Restore the unique constraint dropped for technical reasons
        migrations.AlterUniqueTogether(
            name='dabpermission',
            unique_together={('content_type', 'codename')},
        ),
        # Django does not pick this up automatically because postgres follows the field rename, and Django does not know
        migrations.AddConstraint(
            model_name='objectrole',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type', 'role_definition'), name='one_object_role_per_object_and_role'),
        ),
        # Same subtle postgres issue but with evaluation models
        migrations.AddConstraint(
            model_name='roleevaluation',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type_id', 'codename', 'role'), name='one_entry_per_object_permission_and_role'),
        ),
        migrations.AddConstraint(
            model_name='roleevaluationuuid',
            constraint=models.UniqueConstraint(fields=('object_id', 'content_type_id', 'codename', 'role'), name='one_entry_per_object_permission_and_role_uuid'),
        ),
        migrations.AlterField(
            model_name='dabpermission',
            name='content_type',
            field=models.ForeignKey(help_text='The content type this permission will apply to.', on_delete=models.deletion.CASCADE, to='dab_rbac.dabcontenttype', verbose_name='content type'),
        ),
    ]
