# Generated by Django 4.2.21 on 2025-09-10 17:11
# Modified by Claude (Sonnet 4) - Added object_created field and data migration

from django.db import migrations, models
import django.utils.timezone


def populate_object_created_field(apps, schema_editor):
    """Populate the object_created field for existing role assignments."""
    from ._utils import populate_object_created_field as _populate_object_created_field
    return _populate_object_created_field(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('dab_rbac', '0008_remote_permissions_cleanup'),
    ]

    operations = [
        # Added field for a checksum like purpose for remote models
        migrations.AddField(
            model_name='roleuserassignment',
            name='object_created',
            field=models.DateTimeField(help_text='The created timestamp of related object, if applicable.', null=True),
        ),
        migrations.AddField(
            model_name='roleteamassignment',
            name='object_created',
            field=models.DateTimeField(help_text='The created timestamp of related object, if applicable.', null=True),
        ),
        # Make assignment created timestamp backdateable
        migrations.AlterField(
            model_name='roleteamassignment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date/time this resource was created.'),
        ),
        migrations.AlterField(
            model_name='roleuserassignment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date/time this resource was created.'),
        ),
        # Data migration to populate object_created field
        migrations.RunPython(populate_object_created_field, migrations.RunPython.noop),
    ]
